// Importing Packages //
import { Fragment } from "react"


// Exporting Default function for HomePage //
export default async function Homepage() {
  return (
    <Fragment>
      <div className="my-20">Lorem ipsum dolor sit amet consectetur adipisicing elit. Est omnis officia veritatis accusantium soluta a adipisci dolore sunt id laboriosam rerum, illo aspernatur maiores hic nulla excepturi expedita quod exercitationem possimus dolor illum officiis odio. Vitae, officiis aspernatur necessitatibus nam, quaerat quibusdam amet in eius quia aut quas quae doloremque blanditiis? Eum quo corporis minus maxime praesentium harum dolore odit quasi, ab sit, quis, nulla molestiae. Dolor consectetur possimus voluptatibus sapiente, veritatis saepe at perspiciatis illum ut vel iste eaque deleniti corporis mollitia et dicta. Fugit ipsam maiores neque molestiae, repudiandae illo vero beatae cupiditate voluptatem numquam dignissimos aperiam doloremque saepe iure dolor eveniet vitae. Asperiores provident nesciunt aliquam iste delectus voluptatibus quasi vitae inventore cumque et distinctio nulla cum, alias perferendis blanditiis quod aspernatur eum est molestiae ipsum? Tempora similique facere, vel dolorem consequuntur quas sunt, quia pariatur error aperiam quos, in quo! Quisquam saepe, hic nam earum, esse fugit voluptatum amet debitis iusto possimus quia asperiores laborum qui, beatae sed rerum itaque sapiente! Reprehenderit amet vero odit, fugiat similique asperiores. Blanditiis consectetur magni, commodi itaque debitis cumque doloribus officiis non quibusdam numquam unde possimus consequuntur! Suscipit at eius quaerat odit nemo, doloribus odio totam quam provident accusamus quidem.</div>
      <div className="my-20">Lorem ipsum dolor sit amet consectetur adipisicing elit. Est omnis officia veritatis accusantium soluta a adipisci dolore sunt id laboriosam rerum, illo aspernatur maiores hic nulla excepturi expedita quod exercitationem possimus dolor illum officiis odio. Vitae, officiis aspernatur necessitatibus nam, quaerat quibusdam amet in eius quia aut quas quae doloremque blanditiis? Eum quo corporis minus maxime praesentium harum dolore odit quasi, ab sit, quis, nulla molestiae. Dolor consectetur possimus voluptatibus sapiente, veritatis saepe at perspiciatis illum ut vel iste eaque deleniti corporis mollitia et dicta. Fugit ipsam maiores neque molestiae, repudiandae illo vero beatae cupiditate voluptatem numquam dignissimos aperiam doloremque saepe iure dolor eveniet vitae. Asperiores provident nesciunt aliquam iste delectus voluptatibus quasi vitae inventore cumque et distinctio nulla cum, alias perferendis blanditiis quod aspernatur eum est molestiae ipsum? Tempora similique facere, vel dolorem consequuntur quas sunt, quia pariatur error aperiam quos, in quo! Quisquam saepe, hic nam earum, esse fugit voluptatum amet debitis iusto possimus quia asperiores laborum qui, beatae sed rerum itaque sapiente! Reprehenderit amet vero odit, fugiat similique asperiores. Blanditiis consectetur magni, commodi itaque debitis cumque doloribus officiis non quibusdam numquam unde possimus consequuntur! Suscipit at eius quaerat odit nemo, doloribus odio totam quam provident accusamus quidem.</div>
    </Fragment>
  )
}